import type { Metadata } from "next"
import { Poppins } from "next/font/google"
import "./globals.css"
import Provider from "./provider"
import { Toaster } from "react-hot-toast"

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "700"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Toaster
          toastOptions={{
            success: {
              style: {
                background: "rgb(22, 163, 74)",
                color: "#fff",
              },
            },
            error: {
              style: {
                background: "rgb(220, 38, 38)",
                color: "#fff",
              },
            },
          }}
        />
        <Provider>{children}</Provider>
      </body>
    </html>
  )
}
