import type { Metadata } from "next"
import { Poppins } from "next/font/google"
import { Toaster } from "react-hot-toast"
import StoreProvider from "./StoreProvider"
import "./globals.css"

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "700"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Toaster
          toastOptions={{
            success: {
              style: {
                background: "white",
                color: "green",
              },
            },
            error: {
              style: {
                background: "tomato",
                color: "red",
              },
            },
          }}
        />
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  )
}
